### ISSUE TITLE
Joyce -> Faltou mais casos de teste

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/TDD#3]
https://github.com/VictorPadovan1997/TDD/blob/ddc0b0266083437effbf9afd17f0c8f63edf8176/fizzbuzzTest.php#L30

Aqui vale a mesma observação do #1 :

Poderia explorar mais testes. Exemplo usando 10, 15, 20.

Também faltou testar valores que não são divisíveis por 5, para comprovar que ele não volta "buzz"

**Comment by Massau** [comment]
O meu método que testa o caso em que retorna buzz já está ok.
Desta forma, o que fiz foi inicializar com outros valores a instância do objeto fizzbuzz. Seria isto?

    public function testRetornaBuzz() {
        $fizzbuzz = new FizzBuzz(5,10,15,20);
        $this->assertEquals('buzz', $fizzbuzz->retornaBuzz());
    }
