### ISSUE TITLE
Joyce -> Faltou mais casos de teste

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/TDD#4]
https://github.com/VictorPadovan1997/TDD/blob/ddc0b0266083437effbf9afd17f0c8f63edf8176/fizzbuzzTest.php#L35

Vale a mesma observação do #1 e #3 : 

Poderia explorar mais testes. 

Também faltou testar valores que não são divisíveis por 3, por 5 e por nenhum dos dois, para comprovar que ele não volta "fizzbuzz"

**Comment by Massau** [comment]
O meu método que testa o caso em que retorna fizz já está ok.
Desta forma, o que fiz foi inicializar com outros valores a instância do objeto fizzbuzz. Seria isto?

public function testRetornaFizz() {
        $fizzbuzz = new FizzBuzz(3,6,7);
        $this->assertEquals('fizz', $fizzbuzz->retornaFizz());
    }
