### ISSUE TITLE
Joyce -> Melhorar nomenclatura dos métodos

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/TDD#7]
https://github.com/VictorPadovan1997/TDD/blob/ddc0b0266083437effbf9afd17f0c8f63edf8176/fizzbuzz.php#L10

Isso vale também para os demais métodos, seria mais explicativo:

divisivelPorTres()
divisivelPorCinco()
divisivelPorTresECinco()
...

Porém os métodos já estão retornando "fizzbuzz", então seria mais explicativo:

eFizz()
eBuzz()
eFizzBuzz()
...

**Comment by Massau** [comment]
Eu havia mesmo renomeado da seguinte forma: "dividirPorTres", "dividirPorCinco", "dividirPorAmbos", porém alterei o nome do método para o que ele vai retornar, conforme pontuado
