### ISSUE TITLE
Joyce -> Evitar return dentro do if

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/TDD#8]
https://github.com/VictorPadovan1997/TDD/blob/ddc0b0266083437effbf9afd17f0c8f63edf8176/fizzbuzz.php#L12

Perceba que não há tratamento de um número que não entre na condição do if. Por isso evite return dentro de condicionais, o ideal é iniciar uma variável com um valor padrão e retornar no final do método.

Isso vale também para os outros métodos.

**Comment by Massau** [comment]
Não sei se entendi. O que fiz foi definir que o atributo fizz recebesse a string 'fizz'. Dentro do método em lugar de retornar a string simplesmente, acessei o resultado da string utilizando this e retornei. Seria isto?

public $fizz = 'fizz';

public function retornaFizz($numero = null) {
        if ($this->numero % 3 == 0) { 
            return $this->fizz;
        }
    }
