### ISSUE TITLE
Joyce -> Faltou passo 6 e concluir algorítimo

### ISSUE THREAD

**Issue by joacir** [VictorPadovan1997/TDD#9]
Seria interessante concluir a implementação do passo 6 e também concluir a implementação do algorítimo fizzbuzz para fins de treinamento.

**Comment by Massau** [comment]
Fiz da seguinte forma, retornando o atributo _número_
    public function testRetornaNumero() {
        $fizzbuzz = new FizzBuzz(7);
        $this->assertEquals(7, $fizzbuzz->numero);
    }
